import os

configfile: "config/config.yaml"
report: "workflow.rst"

rawdir = config["datadir"] # the directory with raw BIDS data
outdir = config["outdir"] # the directory where results are to be stored

environmentdir = os.path.join(config["rootdir"], "envs")
resourcedir = os.path.join(config["rootdir"], "resources")
workflowdir = os.path.join(config["rootdir"], "workflow")

# Create the results directory if it doesn't exist already
os.makedirs(outdir, exist_ok=True)

# Specifies the files which should exist at the end of the processing
endfiles = [
    os.path.join(outdir, "derivatives", "static", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-rawFC_relmat.tsv"),
    os.path.join(outdir, "derivatives", "dynamic", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-FCD_relmat.tsv"),
    os.path.join(outdir, "derivatives", "dynamic", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-FCDhistogram_histogram.tsv"),
    os.path.join(outdir, "derivatives", "graph_theory", "global", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-avgClustering_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "global", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-globalEfficiency_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "global", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-assortativity_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "global", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-robustnessRandom_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "global", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-robustnessTargeted_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "global", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-modularity_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "global", "task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-globalMetrics_relmat.tsv"),
    os.path.join(outdir, "derivatives", "graph_theory", "local", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-betweennessCentrality_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "local", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-degreeCentrality_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "local", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-clusteringCoefficient_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "local", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-avgShortestPathLength_relmat.pkl"),
    os.path.join(outdir, "derivatives", "graph_theory", "local", "sub-{subid}", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_desc-participationCoeff_relmat.pkl"),
    # QA outputs
    os.path.join(outdir, "derivatives", "quality_control", "desc-metadataCheck_log.txt"),
    os.path.join(outdir, "derivatives", "quality_control", "figures", "task-rest_desc-maxFramewiseDisplacementScatter_figure.png"),
    os.path.join(outdir, "derivatives", "quality_control", "task-rest_desc-framewiseDisplacement_log.txt"),
    os.path.join(outdir, "derivatives", "quality_control", "sub-{subid}", "figures", "sub-{subid}_task-rest_desc-rawVsClean_figure.png"),
    os.path.join(outdir, "derivatives", "quality_control", "task-rest_desc-denoisingVerification_log.txt"),
    os.path.join(outdir, "derivatives", "quality_control", "figures", "task-rest_desc-qcFcCorrelationHistograms_figure.png"),
    os.path.join(outdir, "derivatives", "quality_control", "figures", "task-rest_desc-qcFcDistanceCorrelation_figure.png"),
    os.path.join(outdir, "derivatives", "quality_control", "task-rest_desc-qcFc_log.txt"),

    os.path.join(outdir, "derivatives", "dataset_description.json")
]

# Define the subject IDs to be processed
excluded = config["excluded_participants"]
subids_all =[subid[4:] for subid in os.listdir(os.path.join(outdir, "bids")) if subid.startswith('sub-') and subid[4:]]
subids = [subid[4:] for subid in os.listdir(os.path.join(outdir, "bids")) if subid.startswith('sub-') and subid[4:] not in excluded]
# subids = [i[4:] for i in os.listdir(rawdir) if i.startswith('sub-')]
# subids = ["LEGK010"]

local_metrics = ["betweennessCentrality", "degreeCentrality", "clusteringCoefficient", "avgShortestPathLength", "participationCoeff"]

rule all:
    """
    Generates all required outputs
    """
    input:
        expand(endfiles, subid=subids, metric=local_metrics),
        expand(os.path.join(outdir, "derivatives", "fmriprep", "sub-{subid}", "func", "sub-{subid}_task-rest_space-fsLR_den-91k_bold.dtseries.nii"), subid=subids_all),
    shell:
        "rm -rf {outdir}/intermediaries && "
        "rm -rf {outdir}/derivatives/atlases && "
        "rm -rf {outdir}/derivatives/conversion"


include: "preprocessing.smk"
include: "create_derivatives.smk"
include: "quality_control.smk"