import os

configfile: "config/config.yaml"
report: "workflow.rst"

rawdir = config["datadir"] # the directory with derivatives to be analysed
outdir = config["outdir"] # the directory where results are to be stored

environmentdir = os.path.join(config["rootdir"], "envs")
resourcedir = os.path.join(config["rootdir"], "resources")
workflowdir = os.path.join(config["rootdir"], "workflow")

# Create the results directory if it doesn't exist already
os.makedirs(outdir, exist_ok=True)

# Specifies the files which should exist at the end of the processing
endfiles = [
    os.path.join(outdir, "results", "static", "images", "avg_fc_comparison.png"),
    os.path.join(outdir, "results", "static", "images", "p_vals_uncorrected.png"),
    os.path.join(outdir, "results", "static", "images", "p_vals_fdr.png"),
    os.path.join(outdir, "results", "dynamic", "images", "avg_FCD_comparison.png"),
    os.path.join(outdir, "results", "dynamic", "images", "avg_FCD_hist_comparison.png"),
    os.path.join(outdir, "results", "dynamic", "images", "avg_FCD_hist_comparison_regr.png"),
    os.path.join(outdir, "results", "graph_theory", "global", "images", "global_metric_comparison.png"),
    os.path.join(outdir, "results", "graph_theory", "local", "{metric}_ps_stats.csv")
]

# Define the subject IDs to be processed
excluded = config["excluded_participants"]
subids = [subid[4:] for subid in os.listdir(os.path.join(rawdir, "xcp_d")) if os.path.exists(os.path.join(rawdir, "xcp_d", f"{subid}", "func", f"{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii")) and subid[4:] not in excluded]

local_metrics = ["betweenness_centrality", "degree_centrality", "clustering_coefficient", "avg_shortest_path_length"]

rule all:
    """
    Generates all required outputs
    """
    input:
        expand(endfiles, subid=subids, metric=local_metrics)

""" ------------------------------------------- """
""" ---------------- The rules ---------------- """
""" ------------------------------------------- """

# Prep

rule get_neat_demo_data:
    input: 
        os.path.join(resourcedir, "demographics.xlsx")
    params:
        workflowdir = workflowdir,
        outdir = outdir
    output: 
        os.path.join(outdir, "intermediaries", "demo_data.csv")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/intermediaries && " 
        "python {params.workflowdir}/scripts/get_neat_demo_data.py --input_file {input} --output_file {output}"

rule create_networks:
    input:
        os.path.join(resourcedir, "atlas-DesikanKilliany_dseg.tsv")
    params:
        resourcedir = resourcedir,
        workflowdir = workflowdir,
        outdir = outdir
    output:
        os.path.join(outdir, "intermediaries", "networks", "networks.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "network_names.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "partition.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "to_delete_network.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "to_delete_partition.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "partition_labels.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/create_networks.py --seg_file {input} --out_dir {params.outdir}/intermediaries/networks"

rule create_raw_fc:
    input:
        exc=os.path.join(outdir, "intermediaries", "networks", "to_delete_network.pkl"),
        ts=os.path.join(rawdir, "xcp_d", "sub-{subid}", "func", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_stat-mean_timeseries.ptseries.nii")
    params:
        workflowdir = workflowdir,
        outdir = outdir
    output:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/static/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/create_raw_fc.py --ts_path {input.ts} --excluded_rois_path {input.exc} --out_path {output}"

rule regress_confounds:
    input:
        expand(os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"), subid=subids),
        demo=os.path.join(outdir, "intermediaries", "demo_data.csv")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        fcdir = os.path.join(outdir, "results", "static"),
        subids=subids
    output:
        expand(os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_regr.csv"), subid=subids)
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/regress_confounds.py --fc_dir {params.fcdir} --subids {params.subids} --demo_data_path {input.demo}"

rule pairwise_comparison:
    input:
        expand(os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_regr.csv"), subid=subids),
        demo=os.path.join(outdir, "intermediaries", "demo_data.csv")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        fcdir = os.path.join(outdir, "results", "static"),
        subids=subids
    output:
        os.path.join(outdir, "results", "static", "avg_nmdare_fc.csv"),
        os.path.join(outdir, "results", "static", "avg_hc_fc.csv"),
        os.path.join(outdir, "results", "static", "p_vals.csv"),
        os.path.join(outdir, "results", "static", "p_vals_fdr.csv"),
        os.path.join(outdir, "results", "static", "stats.csv")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/pairwise_comparison.py --fc_dir {params.fcdir} --subids {params.subids} --demo_data_path {input.demo}"

rule reorder_to_networks:
    input:
        os.path.join(outdir, "results", "static", "avg_nmdare_fc.csv"),
        os.path.join(outdir, "results", "static", "avg_hc_fc.csv"),
        os.path.join(outdir, "results", "static", "p_vals.csv"),
        os.path.join(outdir, "results", "static", "p_vals_fdr.csv"),
        os.path.join(outdir, "results", "static", "stats.csv"),
        os.path.join(outdir, "intermediaries", "networks", "networks.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "network_names.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        networkdir = os.path.join(outdir, "intermediaries", "networks"),
        fcdir = os.path.join(outdir, "results", "static")
    output:
        os.path.join(outdir, "results", "static", "avg_nmdare_fc_reordered.csv"),
        os.path.join(outdir, "results", "static", "avg_hc_fc_reordered.csv"),
        os.path.join(outdir, "results", "static", "p_vals_reordered.csv"),
        os.path.join(outdir, "results", "static", "p_vals_fdr_reordered.csv"),
        os.path.join(outdir, "results", "static", "stats_reordered.csv")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/reorder_to_networks.py --results_dir {params.fcdir} --network_dir {params.networkdir}"

rule plot_pairwise_comparison:
    input:
        os.path.join(outdir, "results", "static", "avg_nmdare_fc_reordered.csv"),
        os.path.join(outdir, "results", "static", "avg_hc_fc_reordered.csv"),
        os.path.join(outdir, "results", "static", "p_vals_reordered.csv"),
        os.path.join(outdir, "results", "static", "p_vals_fdr_reordered.csv"),
        os.path.join(outdir, "results", "static", "stats_reordered.csv"),
        os.path.join(outdir, "intermediaries", "networks", "networks.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "network_names.pkl"),
        expand(os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_regr.csv"), subid=subids),
        demo=os.path.join(outdir, "intermediaries", "demo_data.csv"),
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        fcdir = os.path.join(outdir, "results", "static"),
        subids=subids,
        networkdir = os.path.join(outdir, "intermediaries", "networks")
    output:
        os.path.join(outdir, "results", "static", "images", "avg_fc_comparison.png"),
        os.path.join(outdir, "results", "static", "images", "p_vals_uncorrected.png"),
        os.path.join(outdir, "results", "static", "images", "p_vals_fdr.png")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/plot_pairwise_comparison.py --fc_dir {params.fcdir} --subids {params.subids} --demo_data_path {input.demo} --network_dir {params.networkdir}"

""" ------------------------------------------- """
""" ------- Dynamic FC analysis rules --------- """
""" ------------------------------------------- """

rule create_windowed_fcs:
    input:
        exc=os.path.join(outdir, "intermediaries", "networks", "to_delete_network.pkl"),
        ts=os.path.join(rawdir, "xcp_d", "sub-{subid}", "func", "sub-{subid}_task-rest_space-fsLR_seg-DesikanKilliany_den-91k_stat-mean_timeseries.ptseries.nii")
    params:
        workflowdir = workflowdir,
        outdir = outdir
    output:
        os.path.join(outdir, "results", "dynamic", "sub-{subid}", "sub-{subid}_windowed_FCs.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/dynamic/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/create_windowed_fcs.py --ts_path {input.ts} --excluded_rois_path {input.exc} --out_path {output} --window_size 30 --step_size 1"

# rule regress_windowed_fcs:
#     input:
#         expand(os.path.join(outdir, "results", "dynamic", "sub-{subid}", "sub-{subid}_windowed_FCs.pkl"), subid=subids),
#         demo=os.path.join(outdir, "intermediaries", "demo_data.csv")
#     params:
#         workflowdir = workflowdir,
#         outdir = outdir,
#         fcdir = os.path.join(outdir, "results", "dynamic"),
#         subids=subids
#     output:
#         expand(os.path.join(outdir, "results", "dynamic", "sub-{subid}", "sub-{subid}_windowed_FCs_regr.pkl"), subid=subids)
#     conda:
#         os.path.join(environmentdir, "environment.yaml")
#     shell:
#         "python {params.workflowdir}/scripts/regress_windowed_confounds.py --fc_dir {params.fcdir} --subids {params.subids} --demo_data_path {input.demo}"

rule create_FCDs:
    input:
        os.path.join(outdir, "results", "dynamic", "sub-{subid}", "sub-{subid}_windowed_FCs.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        fcdir = os.path.join(outdir, "results", "dynamic"),
        subids=subids
    output:
        os.path.join(outdir, "results", "dynamic", "sub-{subid}", "sub-{subid}_FCD.csv"),
        os.path.join(outdir, "results", "dynamic", "sub-{subid}", "sub-{subid}_FCD_hist.csv")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/create_FCDs.py --windowed_fc_path {input} --out_dir {params.outdir}/results/dynamic/sub-{wildcards.subid} --subid {wildcards.subid}"

rule aggregate_FCDs:
    input:
        expand(os.path.join(outdir, "results", "dynamic", "sub-{subid}", "sub-{subid}_FCD.csv"), subid=subids),
        expand(os.path.join(outdir, "results", "dynamic", "sub-{subid}", "sub-{subid}_FCD_hist.csv"), subid=subids),
        demo=os.path.join(outdir, "intermediaries", "demo_data.csv")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        subids=subids
    output:
        os.path.join(outdir, "results", "dynamic", "FCDs.pkl"),
        os.path.join(outdir, "results", "dynamic", "FCD_hists.pkl"),
        os.path.join(outdir, "results", "dynamic", "FCD_hists_regr.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/aggregate_FCDs.py --fcds_path {params.outdir}/results/dynamic/ --subids {params.subids} --demo_data_path {input.demo}"

rule plot_FCDs:
    input:
        os.path.join(outdir, "intermediaries", "demo_data.csv"),
        os.path.join(outdir, "results", "dynamic", "FCDs.pkl"),
        os.path.join(outdir, "results", "dynamic", "FCD_hists.pkl"),
        os.path.join(outdir, "results", "dynamic", "FCD_hists_regr.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        subids=subids
    output:
        os.path.join(outdir, "results", "dynamic", "images", "avg_FCD_comparison.png"),
        os.path.join(outdir, "results", "dynamic", "images", "avg_FCD_hist_comparison.png"),
        os.path.join(outdir, "results", "dynamic", "images", "avg_FCD_hist_comparison_regr.png")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/dynamic/images && "
        "python {params.workflowdir}/scripts/plot_FCDs.py --fcds_path {params.outdir}/results/dynamic/ --subids {params.subids} --demo_data_path {input[0]}"

""" ------------------------------------------- """
""" ------ Graph theory analysis rules -------- """
""" ------------------------------------------- """

""" Global metrics """

rule calculate_avg_clustering:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"]
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_avg_clustering.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/global/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_avg_clustering.py --input_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --labels_path {input[1]}"

rule calculate_global_efficiency:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"]
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_global_efficiency.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/global/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_global_efficiency.py --input_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --labels_path {input[1]}"

rule calculate_assortativity:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"]
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_assortativity.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/global/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_assortativity.py --input_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --labels_path {input[1]}"

rule calculate_robustness_random:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"]
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_robustness_random.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/global/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_robustness_random.py --input_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --labels_path {input[1]}"

rule calculate_robustness_targeted:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"]
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_robustness_targeted.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/global/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_robustness_targeted.py --input_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --labels_path {input[1]}"

rule calculate_modularity:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "partition.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "to_delete_partition.pkl"),
        os.path.join(outdir, "intermediaries", "networks", "partition_labels.pkl"),
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"],
        networkdir = os.path.join(outdir, "intermediaries", "networks")
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_modularity.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/global/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_modularity.py --input_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --network_dir {params.networkdir}"

rule calculate_abs_mean_connectivity:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv")
    params:
        workflowdir = workflowdir,
        outdir = outdir
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_abs_mean_connectivity.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/global/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_abs_mean_connectivity.py --input_path {input} --out_path {output}"

rule aggregate_global_metrics:
    input:
        expand(os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_avg_clustering.pkl"), subid=subids),
        expand(os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_global_efficiency.pkl"), subid=subids),
        expand(os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_assortativity.pkl"), subid=subids),
        expand(os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_robustness_random.pkl"), subid=subids),
        expand(os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_robustness_targeted.pkl"), subid=subids),
        expand(os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_modularity.pkl"), subid=subids),
        expand(os.path.join(outdir, "results", "graph_theory", "global", "sub-{subid}", "sub-{subid}_abs_mean_connectivity.pkl"), subid=subids),
        demo=os.path.join(outdir, "intermediaries", "demo_data.csv")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        subids=subids
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "global_metrics.csv")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/aggregate_global_metrics.py --global_metrics_dir {params.outdir}/results/graph_theory/global/ --demo_data_path {input.demo} --out_path {output} --subids {params.subids}"

rule global_metric_group_comparison:
    input:
        os.path.join(outdir, "results", "graph_theory", "global", "global_metrics.csv"),
        demo=os.path.join(outdir, "intermediaries", "demo_data.csv")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        subids=subids
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "global_metric_ps.pkl"),
        os.path.join(outdir, "results", "graph_theory", "global", "global_metric_stats.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/global_metric_comparison.py --metric_path {input[0]} --out_dir {params.outdir}/results/graph_theory/global/ --demo_data_path {input.demo} --subids {params.subids}"

rule plot_global_metrics:
    input:
        os.path.join(outdir, "results", "graph_theory", "global", "global_metrics.csv"),
        os.path.join(outdir, "results", "graph_theory", "global", "global_metric_ps.pkl"),
        os.path.join(outdir, "results", "graph_theory", "global", "global_metric_stats.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir
    output:
        os.path.join(outdir, "results", "graph_theory", "global", "images", "global_metric_comparison.png")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/images && "
        "python {params.workflowdir}/scripts/plot_global_metrics.py --global_metrics_dir {outdir}/results/graph_theory/global/"

""" Local metrics """

rule calculate_betweenness_centrality:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"]
    output:
        os.path.join(outdir, "results", "graph_theory", "local", "sub-{subid}", "sub-{subid}_betweenness_centrality.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/local/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_betweenness_centrality.py --fc_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --labels_path {input[1]}"

rule calculate_degree_centrality:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"]
    output:
        os.path.join(outdir, "results", "graph_theory", "local", "sub-{subid}", "sub-{subid}_degree_centrality.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/local/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_degree_centrality.py --fc_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --labels_path {input[1]}"

rule calculate_clustering_coefficient:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"]
    output:
        os.path.join(outdir, "results", "graph_theory", "local", "sub-{subid}", "sub-{subid}_clustering_coefficient.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/local/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_clustering_coefficient.py --fc_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --labels_path {input[1]}"

rule calculate_avg_shortest_path_length:
    input:
        os.path.join(outdir, "results", "static", "sub-{subid}", "sub-{subid}_FC_raw.csv"),
        os.path.join(outdir, "intermediaries", "networks", "network_labels.pkl")
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        min_density = config["min_density"],
        max_density = config["max_density"],
        density_step = config["density_step"]
    output:
        os.path.join(outdir, "results", "graph_theory", "local", "sub-{subid}", "sub-{subid}_avg_shortest_path_length.pkl")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "mkdir -p {params.outdir}/results/graph_theory/local/sub-{wildcards.subid} && "
        "python {params.workflowdir}/scripts/calculate_avg_shortest_path_length.py --fc_path {input[0]} --out_path {output} --min_density {params.min_density} --max_density {params.max_density} --density_step {params.density_step} --labels_path {input[1]}"

rule aggregate_local_metrics:
    input:
        expand(os.path.join(outdir, "results", "graph_theory", "local", "sub-{subid}", "sub-{subid}_betweenness_centrality.pkl"), subid=subids),
        expand(os.path.join(outdir, "results", "graph_theory", "local", "sub-{subid}", "sub-{subid}_degree_centrality.pkl"), subid=subids),
        expand(os.path.join(outdir, "results", "graph_theory", "local", "sub-{subid}", "sub-{subid}_clustering_coefficient.pkl"), subid=subids),
        expand(os.path.join(outdir, "results", "graph_theory", "local", "sub-{subid}", "sub-{subid}_avg_shortest_path_length.pkl"), subid=subids)
    params:
        workflowdir = workflowdir,
        outdir = outdir,
        subids = subids
    output:
        os.path.join(outdir, "results", "graph_theory", "local", "betweenness_centrality_aggregated.csv"),
        os.path.join(outdir, "results", "graph_theory", "local", "degree_centrality_aggregated.csv"),
        os.path.join(outdir, "results", "graph_theory", "local", "clustering_coefficient_aggregated.csv"),
        os.path.join(outdir, "results", "graph_theory", "local", "avg_shortest_path_length_aggregated.csv")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/aggregate_local_metrics.py --results_dir {params.outdir}/results/graph_theory/local/ --subids {params.subids}"

rule local_metric_comparison:
    input:
        os.path.join(outdir, "results", "graph_theory", "local", "{metric}_aggregated.csv"),
        demo=os.path.join(outdir, "intermediaries", "demo_data.csv")
    params:
        workflowdir = workflowdir,
        outdir = outdir
    output:
        os.path.join(outdir, "results", "graph_theory", "local", "{metric}_ps_stats.csv")
    conda:
        os.path.join(environmentdir, "environment.yaml")
    shell:
        "python {params.workflowdir}/scripts/local_metric_comparison.py --res_dir {params.outdir}/results/graph_theory/local --metric {wildcards.metric} --demo_data_path {input[1]}"

# rule local_metric_plotting:
#     input:
#         os.path.join(outdir, "results", "graph_theory", "local", "{metric}_ps_stats.csv"),
#         os.path.join(resourcedir, "atlas-desikankilliany.nii.gz")
#     params:
#         workflowdir = workflowdir,
#         outdir = outdir
#     output:
#         os.path.join(outdir, "results", "graph_theory", "local", "images", "{metric}_plot.png"),
#         os.path.join(outdir, "results", "graph_theory", "local", "images", "{metric}_plot_fdr.png")
#     conda:
#         os.path.join(environmentdir, "environment.yaml")
#     shell:
#         "mkdir -p {params.outdir}/results/graph_theory/local/images &&"
#         "python {params.workflowdir}/scripts/local_metric_plotting.py --res_dir {params.outdir}/results/graph_theory/local --metric {wildcards.metric}s --atlas_img {input[1]}"