datadir:  "/Users/brainsimulation/Desktop/derivatives_dk_T2uniform/derivatives"
rootdir: "/Users/brainsimulation/Desktop/nmdare-analysis/"
outdir: "/Users/brainsimulation/Desktop/nmdare-analysis/out"

excluded_participants:
  - RSGK017
  - LENMDA001
  - LENMDA006
  - LENMDA172
  - LENMDA187
  - LENMDA191

min_density: 0.1
max_density: 0.6
density_step: 0.05